import os
import json
import requests

def generate_questions_with_gemini(board, standard, subject, num_questions=10):
    """
    Calls Google Gemini API via REST to generate Quiz Questions in the required 3-language JSON format.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise Exception("GEMINI_API_KEY is not set in the environment variables. Please add it to your server configuration.")
        
    prompt = f"""
Act as a Senior Education Content Creator for {board} Board.
I am building a multilingual educational Quiz Game.

Please generate {num_questions} real, curriculum-based MCQ questions for:
Standard: {standard}
Subject: {subject}

For every question, you MUST provide the text in 3 languages: English, Gujarati, and Hindi.

Return ONLY a valid JSON array. Do not add any extra text, markdown formatting, or ```json tags outside the JSON.

Use this EXACT JSON structure for each question:
[
    {{
        "board": "{board}",
        "standard": "{standard}",
        "stream": "General",
        "subject": "{subject}",
        "chapter": "Appropriate Chapter Name Here",
        "topic": "Appropriate Topic Name Here",
        "difficulty": "Medium",
        "question": {{
            "en": "English question text",
            "gu": "Gujarati question text",
            "hi": "Hindi question text"
        }},
        "options": {{
            "en": ["Option A", "Option B", "Option C", "Option D"],
            "gu": ["Option A", "Option B", "Option C", "Option D"],
            "hi": ["Option A", "Option B", "Option C", "Option D"]
        }},
        "correct_option": "A",
        "explanation": {{
            "en": "English explanation",
            "gu": "Gujarati explanation",
            "hi": "Hindi explanation"
        }},
        "source": "{board} Textbook",
        "source_type": "Official",
        "verified": true
    }}
]

Generate exactly {num_questions} distinct, accurate questions.
"""
    # Dynamic Model Resolution to prevent 404 errors
    models_url = f"https://generativelanguage.googleapis.com/v1beta/models?key={api_key}"
    available_models = []
    try:
        models_response = requests.get(models_url)
        if models_response.status_code == 200:
            models_data = models_response.json()
            for m in models_data.get('models', []):
                if 'generateContent' in m.get('supportedGenerationMethods', []):
                    name = m.get('name', '')
                    if name.startswith('models/'):
                        name = name[7:]
                    available_models.append(name)
    except Exception:
        pass
        
    if not available_models:
        # Hardcoded fallback list if fetch fails
        available_models = [
            'gemini-3.6-flash', 'gemini-3.5-flash', 'gemini-3.5-flash-lite',
            'gemini-3.1-pro', 'gemini-2.5-flash', 'gemini-1.5-flash', 'gemini-pro'
        ]
        
    # Prioritized list of models for 2026
    pref_list = [
        'gemini-3.6-flash',
        'gemini-3.5-flash',
        'gemini-3.5-flash-lite',
        'gemini-3.1-pro',
        'gemini-2.5-pro',
        'gemini-2.5-flash',
        'gemini-1.5-flash',
        'gemini-pro'
    ]
    
    # Sort available models by preference
    target_models = []
    for pref in pref_list:
        if pref in available_models:
            target_models.append(pref)
            
    # Append any remaining models just in case
    for m in available_models:
        if m not in target_models:
            target_models.append(m)
            
    if not target_models:
        raise Exception("No generative models available for this API key.")
        
    headers = {
        "Content-Type": "application/json"
    }
    
    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            "temperature": 0.2,
            "responseMimeType": "application/json"
        }
    }
    
    last_error = None
    for target_model in target_models:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{target_model}:generateContent?key={api_key}"
        try:
            response = requests.post(url, headers=headers, json=payload)
            
            if response.status_code != 200:
                error_msg = response.json().get('error', {}).get('message', 'Unknown API Error')
                # If it's a 404 or 403 related to model availability, try the next model
                if response.status_code == 404 or "no longer available" in error_msg:
                    last_error = f"{target_model}: {error_msg}"
                    continue
                raise Exception(f"API Error ({response.status_code}): {error_msg}")
                
            result = response.json()
            
            if 'candidates' not in result or not result['candidates']:
                raise Exception("No content generated by AI")
                
            text_output = result['candidates'][0]['content']['parts'][0]['text']
            
            # Clean up markdown if AI included it despite strict mime type
            if text_output.startswith("```json"):
                text_output = text_output.replace("```json", "", 1)
            if text_output.startswith("```"):
                text_output = text_output.replace("```", "", 1)
            if text_output.endswith("```"):
                text_output = text_output[::-1].replace("```", "", 1)[::-1]
                
            data = json.loads(text_output.strip())
            return data
            
        except json.JSONDecodeError as e:
            last_error = f"The AI generated incomplete or invalid data. Please try again with fewer questions. (Error: {str(e)})"
            continue # Try next model
        except Exception as e:
            # If it's a structural error, don't retry models
            if "API Error" not in str(e) and "no longer available" not in str(e):
                raise Exception(f"An unexpected error occurred: {str(e)}")
            last_error = str(e)
            
    raise Exception(f"Failed to generate questions. All available AI models failed. Last error: {last_error}")
